### ISSUE TITLE
Formal Verification

### ISSUE THREAD

**Issue by colin-morpho** [morpho-org/morpho-token#84]
Meta issue to track the verification progress and requirements.

The mention "up to upgrade" means that the specs are proven assuming that an upgrade doesn't change the storage.
This assumption makes sense as the specs are ensured for a given implementation.
That is should the implementation change, the specs are not expected to hold anymore and then the new specs need to be proven.

## TODO
- [x] minimal certora setup, #90
## Verified Properties:
- [x] reentrancy safety, see #90 ;
- [x] immutability property, up to upgrade see #90 ;
- [x] ERC20 compliance + mint and burn, up to upgrade, see #91, #93 and #98;
- [x] Delegation correctness, up to upgrade, see #92 and #102.
